<p style="font-size: 14px;">Коллектив нашего предприятия будет всегла рад выслушать Ваши запросы и пожелания по следующим телефонам и адресам</p>
<center style="font-size: 14px;"><b>Адрес ООО "Дельта"</b></center>
<p style="font-size: 14px;">Наше предпиятие расположено по адресу: ул. Ворошилова, 12 г. Днепропетровск, Украина 49027<br>
E-mail: <a href="mailto:info@delta.in.ua">info@delta.in.ua</a><br>
http:// <a href="http://www.delta.in.ua/">www.delta.in.ua</a></p>
<p style="font-size: 14px;">Интересующую и необходимую Вам информацию вы можете получить по следующим телефонам:</p>
<center style="font-size: 14px;"><b>в г. Днепропетровске</b></center>
<p style="font-size: 14px;">
<li> приемная, директор: +38 056 3701374;</li>
<li> первый заместитель директора: +38 056 7911601;</li>
<li> заместитель директора по техническим вопросам: +38 056 7911602;</li>
<li> отдел маркетинга: +38 056 7911466;</li>
<li> отдел продаж: +38 056 7911486</li>
</p>
<center style="font-size: 14px;"><b>в г. Измаиле, Одесской обл.</b></center>
<p style="font-size: 14px;">
<li> представительство в г. Измаил: +38 04843 38525;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;+38 04843 40935</li>
</p>
<center style="font-size: 14px;"><b>в г. Калуше, Ивано-Франковской обл.</b></center>
<p style="font-size: 14px;">
<li> представительство в г. Калуш: +38 03472 60330;</li>
</p>


