<?
if (!$id)
{
header ("location: http://www.delta.in.ua/?id=40");
}
else
{
}
?>
<html>
<head>

<!-- CHANGE THE NEXT THREE LINES -->

	<title>ООО Дельта - Инструмент, оборудование, оснастка...</title>

<meta name="Description" content="AllWebCo Website Templates and Pre-Made Websites. Very reasonable prices and a complete setup.">
<meta name="KeyWords" content="website template, template, pre made web site, instant website,pre-made website,instant webpage,pre-made webpage">

<!-- CHANGE THE ABOVE THREE LINES -->



<meta http-equiv="Content-Type" content="text/html; charset=ANSI-1251">
<META name="Publisher" content="AllWebCo Webpage Design http://allwebcodesign.com/">
<META name="revisit-after" content="15 days">
<META name="robots" content="index, follow">
<META name="Robots" content="All">



<link rel=StyleSheet href="coolstyle.css" type="text/css" media="screen">

<script language="JavaScript" src="pop-closeup.js"></script>
<script language="JavaScript" src="javascripts.js"></script>





</head>

<BODY BGCOLOR="#FFFFFF" background="picts/background-main.gif" TEXT="#000000" LINK="#0033CC" VLINK="#0033CC" ALINK="#0033CC" leftmargin="0" rightmargin="0" topmargin="0" bottommargin="0" marginheight="0" marginwidth="0">


<!-- OUTER TABLE-->
<TABLE cellpadding="0" cellspacing="0" border="0" width="100%" height="99%"><tr><td VALIGN="top">


<script language="JavaScript" src="menu_header.js"></script>




