<form target="_blank" action="mailer.php" method="post">
<table align="center">
<tbody>
<tr valign="top">
<td>
<p align="right"><strong>Ваше имя:</strong></p></td>
<td width="15">&nbsp; </td>
<td><input class="c" size="30" name="fio" /></td></tr><tr valign="top">
<td>
<p align="right">Компания:</p></td>
<td>&nbsp; </td>
<td><input class="c" size="30" name="Company" /></td></tr>
<tr valign="top">
<td>
<p align="right"><strong>Город:</strong></p></td>
<td>&nbsp; </td>
<td>
<input class="c" name="city" size="30" />
</td></tr>
<tr valign="top">
<td>
<p align="right"><strong>Ваш e-mail:</strong></p></td>
<td></td>
<td><input class="c" size="30" name="FROM" />
</td>
</tr>
<tr valign="top">
<td>
<p align="right"><strong>Телефон:</strong></p></td>
<td>&nbsp; </td>
<td><input class="c" size="30" name="Phone" />&nbsp;<br />
</td></tr>
<tr valign="top">
<td></td>
<td>&nbsp; </td>
<td></td></tr>
<tr valign="top">
<td>
<p align="right"><strong>Выберете категорию</strong></p></td>
<td></td>
<td><select style="WIDTH: 203px" name="WhereHeard">
<option selected="selected"> - - - </option>
<option>Оборудование</option>
<option>Инструмент</option>
<option>Оснастка</option>
<option>Технические средства</option>
<option>Всё</option>
</select>
</td>
</tr>
<tr valign="top">
<td></td>
<td>&nbsp; </td>
<td></td></tr>
<tr valign="top">
<td>
<p align="right">Коментарий к запросу:</p></td><td>&nbsp; </td>
<td><textarea style="WIDTH: 379px; HEIGHT: 152px" name="Comments" rows="8" cols="40">
</textarea>
</td></tr>
<tr valign="top">
<td>
<p align="right"><strong></strong></p></td>
<td>&nbsp; </td>
<td></td></tr>
<tr valign="top">
<td>
<p align="right"><strong></strong></p></td>
<td>&nbsp; </td>
<td>
<input class="b" name="" type="reset" value="Сброс">
<input class="b" name="" type="submit" value="Отправить">
</td></tr><tr valign="top">
<td>
<p align="right"><strong></strong></p></td>
<td>&nbsp; </td>
<td><p align="left"></p></td></tr></tbody></table>
</form>